export interface City {
  name: string;
  state: string;
  pincode: string;
  category: 'A' | 'B' | 'C';
}

export type Platform = 'carwale' | 'olx' | 'both' | 'none' | null;
export type PackageType = 'gold' | 'diamond' | null;
export type Step = 'basic' | 'location' | 'platform' | 'details' | 'whatsapp' | 'pricing' | 'success';

export interface OnboardingData {
  dealershipName: string;
  email: string;
  selectedState: string;
  primaryCity: City | null;
  pincode: string;
  packageType: PackageType;
  city2: City | null;
  city3: City | null;
  platform: Platform;
  carWaleNumber: string;
  olxNumber: string;
  singleMobileNumber: string;
  isCarWaleVerified: boolean;
  isOlxVerified: boolean;
  isSingleVerified: boolean;
  whatsappNumberSource: 'carwale' | 'olx' | 'single' | 'custom' | null;
  customWhatsappNumber: string;
  useSuperDost: boolean;
}

export const INDIAN_CITIES: City[] = [
  // Andaman and Nicobar Islands
  { name: 'Port Blair', state: 'Andaman and Nicobar Islands', pincode: '', category: 'B' },
  // Andhra Pradesh
  { name: 'Adoni', state: 'Andhra Pradesh', pincode: '', category: 'C' },
  { name: 'Amaravati', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Anantapur', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Chandragiri', state: 'Andhra Pradesh', pincode: '', category: 'C' },
  { name: 'Chittoor', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Dowlaiswaram', state: 'Andhra Pradesh', pincode: '', category: 'C' },
  { name: 'Eluru', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Guntur', state: 'Andhra Pradesh', pincode: '', category: 'A' },
  { name: 'Kadapa', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Kakinada', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Kurnool', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Machilipatnam', state: 'Andhra Pradesh', pincode: '', category: 'C' },
  { name: 'Nagarjunakoṇḍa', state: 'Andhra Pradesh', pincode: '', category: 'C' },
  { name: 'Rajahmundry', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Srikakulam', state: 'Andhra Pradesh', pincode: '', category: 'C' },
  { name: 'Tirupati', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Vijayawada', state: 'Andhra Pradesh', pincode: '520001', category: 'A' },
  { name: 'Visakhapatnam', state: 'Andhra Pradesh', pincode: '530001', category: 'A' },
  { name: 'Vizianagaram', state: 'Andhra Pradesh', pincode: '', category: 'B' },
  { name: 'Yemmiganur', state: 'Andhra Pradesh', pincode: '', category: 'C' },
  // Arunachal Pradesh
  { name: 'Itanagar', state: 'Arunachal Pradesh', pincode: '', category: 'B' },
  // Assam
  { name: 'Dhuburi', state: 'Assam', pincode: '', category: 'C' },
  { name: 'Dibrugarh', state: 'Assam', pincode: '', category: 'B' },
  { name: 'Dispur', state: 'Assam', pincode: '', category: 'B' },
  { name: 'Guwahati', state: 'Assam', pincode: '781001', category: 'A' },
  { name: 'Jorhat', state: 'Assam', pincode: '', category: 'B' },
  { name: 'Nagaon', state: 'Assam', pincode: '', category: 'B' },
  { name: 'Sivasagar', state: 'Assam', pincode: '', category: 'B' },
  { name: 'Silchar', state: 'Assam', pincode: '', category: 'B' },
  { name: 'Tezpur', state: 'Assam', pincode: '', category: 'B' },
  { name: 'Tinsukia', state: 'Assam', pincode: '', category: 'B' },
  // Bihar
  { name: 'Ara', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Barauni', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Begusarai', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Bettiah', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Bhagalpur', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Bihar Sharif', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Bodh Gaya', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Buxar', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Chapra', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Darbhanga', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Dehri', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Dinapur Nizamat', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Gaya', state: 'Bihar', pincode: '823001', category: 'B' },
  { name: 'Hajipur', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Jamalpur', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Katihar', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Madhubani', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Motihari', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Munger', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Muzaffarpur', state: 'Bihar', pincode: '842001', category: 'B' },
  { name: 'Patna', state: 'Bihar', pincode: '800001', category: 'A' },
  { name: 'Purnia', state: 'Bihar', pincode: '', category: 'B' },
  { name: 'Pusa', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Saharsa', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Samastipur', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Sasaram', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Sitamarhi', state: 'Bihar', pincode: '', category: 'C' },
  { name: 'Siwan', state: 'Bihar', pincode: '', category: 'C' },
  // Chandigarh
  { name: 'Chandigarh', state: 'Chandigarh', pincode: '160017', category: 'A' },
  // Chhattisgarh
  { name: 'Ambikapur', state: 'Chhattisgarh', pincode: '', category: 'C' },
  { name: 'Bhilai', state: 'Chhattisgarh', pincode: '490001', category: 'B' },
  { name: 'Bilaspur', state: 'Chhattisgarh', pincode: '495001', category: 'B' },
  { name: 'Dhamtari', state: 'Chhattisgarh', pincode: '', category: 'C' },
  { name: 'Durg', state: 'Chhattisgarh', pincode: '', category: 'B' },
  { name: 'Jagdalpur', state: 'Chhattisgarh', pincode: '', category: 'C' },
  { name: 'Raipur', state: 'Chhattisgarh', pincode: '492001', category: 'A' },
  { name: 'Rajnandgaon', state: 'Chhattisgarh', pincode: '', category: 'B' },
  // Dadra and Nagar Haveli and Daman and Diu
  { name: 'Daman', state: 'Dadra and Nagar Haveli and Daman and Diu', pincode: '', category: 'B' },
  { name: 'Diu', state: 'Dadra and Nagar Haveli and Daman and Diu', pincode: '', category: 'C' },
  { name: 'Silvassa', state: 'Dadra and Nagar Haveli and Daman and Diu', pincode: '', category: 'B' },
  // Delhi
  { name: 'Delhi', state: 'Delhi', pincode: '110001', category: 'A' },
  { name: 'New Delhi', state: 'Delhi', pincode: '110001', category: 'A' },
  // Goa
  { name: 'Madgaon', state: 'Goa', pincode: '', category: 'B' },
  { name: 'Panaji', state: 'Goa', pincode: '', category: 'B' },
  // Gujarat
  { name: 'Ahmadabad', state: 'Gujarat', pincode: '380001', category: 'A' },
  { name: 'Amreli', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Bharuch', state: 'Gujarat', pincode: '', category: 'B' },
  { name: 'Bhavnagar', state: 'Gujarat', pincode: '364001', category: 'B' },
  { name: 'Bhuj', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Dwarka', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Gandhinagar', state: 'Gujarat', pincode: '382010', category: 'A' },
  { name: 'Godhra', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Jamnagar', state: 'Gujarat', pincode: '361001', category: 'B' },
  { name: 'Junagadh', state: 'Gujarat', pincode: '', category: 'B' },
  { name: 'Kandla', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Khambhat', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Kheda', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Mahesana', state: 'Gujarat', pincode: '', category: 'B' },
  { name: 'Morbi', state: 'Gujarat', pincode: '', category: 'B' },
  { name: 'Nadiad', state: 'Gujarat', pincode: '', category: 'B' },
  { name: 'Navsari', state: 'Gujarat', pincode: '', category: 'B' },
  { name: 'Okha', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Palanpur', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Patan', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Porbandar', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Rajkot', state: 'Gujarat', pincode: '360001', category: 'B' },
  { name: 'Surat', state: 'Gujarat', pincode: '395001', category: 'A' },
  { name: 'Surendranagar', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Valsad', state: 'Gujarat', pincode: '', category: 'C' },
  { name: 'Veraval', state: 'Gujarat', pincode: '', category: 'C' },
  // Haryana
  { name: 'Ambala', state: 'Haryana', pincode: '133001', category: 'B' },
  { name: 'Bhiwani', state: 'Haryana', pincode: '', category: 'C' },
  { name: 'Chandigarh', state: 'Haryana', pincode: '160017', category: 'A' },
  { name: 'Faridabad', state: 'Haryana', pincode: '121001', category: 'A' },
  { name: 'Firozpur Jhirka', state: 'Haryana', pincode: '', category: 'C' },
  { name: 'Gurugram', state: 'Haryana', pincode: '122001', category: 'A' },
  { name: 'Hansi', state: 'Haryana', pincode: '', category: 'C' },
  { name: 'Hisar', state: 'Haryana', pincode: '125001', category: 'B' },
  { name: 'Jind', state: 'Haryana', pincode: '', category: 'B' },
  { name: 'Kaithal', state: 'Haryana', pincode: '', category: 'B' },
  { name: 'Karnal', state: 'Haryana', pincode: '132001', category: 'B' },
  { name: 'Kurukshetra', state: 'Haryana', pincode: '', category: 'B' },
  { name: 'Panipat', state: 'Haryana', pincode: '132103', category: 'B' },
  { name: 'Pehowa', state: 'Haryana', pincode: '', category: 'C' },
  { name: 'Rewari', state: 'Haryana', pincode: '', category: 'C' },
  { name: 'Rohtak', state: 'Haryana', pincode: '124001', category: 'B' },
  { name: 'Sirsa', state: 'Haryana', pincode: '', category: 'B' },
  { name: 'Sonipat', state: 'Haryana', pincode: '131001', category: 'B' },
  // Himachal Pradesh
  { name: 'Bilaspur', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Chamba', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Dalhousie', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Dharmshala', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Hamirpur', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Kangra', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Kullu', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Mandi', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Nahan', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  { name: 'Shimla', state: 'Himachal Pradesh', pincode: '171001', category: 'B' },
  { name: 'Una', state: 'Himachal Pradesh', pincode: '', category: 'C' },
  // Jammu and Kashmir
  { name: 'Anantnag', state: 'Jammu and Kashmir', pincode: '', category: 'B' },
  { name: 'Baramula', state: 'Jammu and Kashmir', pincode: '', category: 'C' },
  { name: 'Doda', state: 'Jammu and Kashmir', pincode: '', category: 'C' },
  { name: 'Gulmarg', state: 'Jammu and Kashmir', pincode: '', category: 'C' },
  { name: 'Jammu', state: 'Jammu and Kashmir', pincode: '180001', category: 'B' },
  { name: 'Kathua', state: 'Jammu and Kashmir', pincode: '', category: 'C' },
  { name: 'Punch', state: 'Jammu and Kashmir', pincode: '', category: 'C' },
  { name: 'Rajouri', state: 'Jammu and Kashmir', pincode: '', category: 'C' },
  { name: 'Srinagar', state: 'Jammu and Kashmir', pincode: '190001', category: 'A' },
  { name: 'Udhampur', state: 'Jammu and Kashmir', pincode: '', category: 'C' },
  // Jharkhand
  { name: 'Bokaro', state: 'Jharkhand', pincode: '827001', category: 'B' },
  { name: 'Chaibasa', state: 'Jharkhand', pincode: '', category: 'C' },
  { name: 'Deoghar', state: 'Jharkhand', pincode: '', category: 'C' },
  { name: 'Dhanbad', state: 'Jharkhand', pincode: '826001', category: 'B' },
  { name: 'Dumka', state: 'Jharkhand', pincode: '', category: 'C' },
  { name: 'Giridih', state: 'Jharkhand', pincode: '', category: 'C' },
  { name: 'Hazaribag', state: 'Jharkhand', pincode: '', category: 'C' },
  { name: 'Jamshedpur', state: 'Jharkhand', pincode: '831001', category: 'A' },
  { name: 'Jharia', state: 'Jharkhand', pincode: '', category: 'C' },
  { name: 'Rajmahal', state: 'Jharkhand', pincode: '', category: 'C' },
  { name: 'Ranchi', state: 'Jharkhand', pincode: '834001', category: 'A' },
  { name: 'Saraikela', state: 'Jharkhand', pincode: '', category: 'C' },
  // Karnataka
  { name: 'Badami', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Ballari', state: 'Karnataka', pincode: '', category: 'B' },
  { name: 'Bengaluru', state: 'Karnataka', pincode: '560001', category: 'A' },
  { name: 'Belagavi', state: 'Karnataka', pincode: '590001', category: 'B' },
  { name: 'Bhadravati', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Bidar', state: 'Karnataka', pincode: '', category: 'B' },
  { name: 'Chikkamagaluru', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Chitradurga', state: 'Karnataka', pincode: '', category: 'B' },
  { name: 'Davangere', state: 'Karnataka', pincode: '577001', category: 'B' },
  { name: 'Halebid', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Hassan', state: 'Karnataka', pincode: '', category: 'B' },
  { name: 'Hubballi-Dharwad', state: 'Karnataka', pincode: '580001', category: 'B' },
  { name: 'Kalaburagi', state: 'Karnataka', pincode: '585101', category: 'B' },
  { name: 'Kolar', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Madikeri', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Mandya', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Mangaluru', state: 'Karnataka', pincode: '575001', category: 'B' },
  { name: 'Mysuru', state: 'Karnataka', pincode: '570001', category: 'B' },
  { name: 'Raichur', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Shivamogga', state: 'Karnataka', pincode: '', category: 'B' },
  { name: 'Shravanabelagola', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Shrirangapattana', state: 'Karnataka', pincode: '', category: 'C' },
  { name: 'Tumakuru', state: 'Karnataka', pincode: '572101', category: 'B' },
  { name: 'Vijayapura', state: 'Karnataka', pincode: '', category: 'B' },
  // Kerala
  { name: 'Alappuzha', state: 'Kerala', pincode: '', category: 'B' },
  { name: 'Vatakara', state: 'Kerala', pincode: '', category: 'C' },
  { name: 'Idukki', state: 'Kerala', pincode: '', category: 'C' },
  { name: 'Kannur', state: 'Kerala', pincode: '670001', category: 'B' },
  { name: 'Kochi', state: 'Kerala', pincode: '682001', category: 'A' },
  { name: 'Kollam', state: 'Kerala', pincode: '691001', category: 'B' },
  { name: 'Kottayam', state: 'Kerala', pincode: '', category: 'B' },
  { name: 'Kozhikode', state: 'Kerala', pincode: '673001', category: 'B' },
  { name: 'Mattancheri', state: 'Kerala', pincode: '', category: 'C' },
  { name: 'Palakkad', state: 'Kerala', pincode: '', category: 'B' },
  { name: 'Thalassery', state: 'Kerala', pincode: '', category: 'C' },
  { name: 'Thiruvananthapuram', state: 'Kerala', pincode: '695001', category: 'A' },
  { name: 'Thrissur', state: 'Kerala', pincode: '680001', category: 'B' },
  // Ladakh
  { name: 'Kargil', state: 'Ladakh', pincode: '', category: 'C' },
  { name: 'Leh', state: 'Ladakh', pincode: '', category: 'C' },
  // Madhya Pradesh
  { name: 'Balaghat', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Barwani', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Betul', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Bharhut', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Bhind', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Bhojpur', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Bhopal', state: 'Madhya Pradesh', pincode: '462001', category: 'A' },
  { name: 'Burhanpur', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Chhatarpur', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Chhindwara', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Damoh', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Datia', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Dewas', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Dhar', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Dr. Ambedkar Nagar (Mhow)', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Guna', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Gwalior', state: 'Madhya Pradesh', pincode: '474001', category: 'B' },
  { name: 'Hoshangabad', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Indore', state: 'Madhya Pradesh', pincode: '452001', category: 'A' },
  { name: 'Itarsi', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Jabalpur', state: 'Madhya Pradesh', pincode: '482001', category: 'B' },
  { name: 'Jhabua', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Khajuraho', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Khandwa', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Khargone', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Maheshwar', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Mandla', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Mandsaur', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Morena', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Murwara', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Narsimhapur', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Narsinghgarh', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Narwar', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Neemuch', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Nowgong', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Orchha', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Panna', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Raisen', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Rajgarh', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Ratlam', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Rewa', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Sagar', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Sarangpur', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Satna', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Sehore', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Seoni', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Shahdol', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Shajapur', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Sheopur', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Shivpuri', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  { name: 'Ujjain', state: 'Madhya Pradesh', pincode: '456001', category: 'B' },
  { name: 'Vidisha', state: 'Madhya Pradesh', pincode: '', category: 'C' },
  // Maharashtra
  { name: 'Ahmadnagar', state: 'Maharashtra', pincode: '', category: 'B' },
  { name: 'Akola', state: 'Maharashtra', pincode: '444001', category: 'B' },
  { name: 'Amravati', state: 'Maharashtra', pincode: '444601', category: 'B' },
  { name: 'Aurangabad', state: 'Maharashtra', pincode: '431001', category: 'A' },
  { name: 'Bhandara', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Bhusawal', state: 'Maharashtra', pincode: '', category: 'B' },
  { name: 'Bid', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Buldhana', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Chandrapur', state: 'Maharashtra', pincode: '442401', category: 'B' },
  { name: 'Daulatabad', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Dhule', state: 'Maharashtra', pincode: '424001', category: 'B' },
  { name: 'Jalgaon', state: 'Maharashtra', pincode: '425001', category: 'B' },
  { name: 'Kalyan', state: 'Maharashtra', pincode: '421301', category: 'A' },
  { name: 'Karli', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Kolhapur', state: 'Maharashtra', pincode: '416001', category: 'B' },
  { name: 'Mahabaleshwar', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Malegaon', state: 'Maharashtra', pincode: '', category: 'B' },
  { name: 'Matheran', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Mumbai', state: 'Maharashtra', pincode: '400001', category: 'A' },
  { name: 'Nagpur', state: 'Maharashtra', pincode: '440001', category: 'A' },
  { name: 'Nanded', state: 'Maharashtra', pincode: '431601', category: 'B' },
  { name: 'Nashik', state: 'Maharashtra', pincode: '422001', category: 'A' },
  { name: 'Osmanabad', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Pandharpur', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Parbhani', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Pune', state: 'Maharashtra', pincode: '411001', category: 'A' },
  { name: 'Ratnagiri', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Sangli', state: 'Maharashtra', pincode: '416416', category: 'B' },
  { name: 'Satara', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Sevagram', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Solapur', state: 'Maharashtra', pincode: '413001', category: 'B' },
  { name: 'Thane', state: 'Maharashtra', pincode: '400601', category: 'A' },
  { name: 'Ulhasnagar', state: 'Maharashtra', pincode: '421001', category: 'B' },
  { name: 'Vasai-Virar', state: 'Maharashtra', pincode: '401201', category: 'A' },
  { name: 'Wardha', state: 'Maharashtra', pincode: '', category: 'C' },
  { name: 'Yavatmal', state: 'Maharashtra', pincode: '', category: 'C' },
  // Manipur
  { name: 'Imphal', state: 'Manipur', pincode: '', category: 'B' },
  // Meghalaya
  { name: 'Cherrapunji', state: 'Meghalaya', pincode: '', category: 'C' },
  { name: 'Shillong', state: 'Meghalaya', pincode: '', category: 'B' },
  // Mizoram
  { name: 'Aizawl', state: 'Mizoram', pincode: '', category: 'B' },
  { name: 'Lunglei', state: 'Mizoram', pincode: '', category: 'C' },
  // Nagaland
  { name: 'Kohima', state: 'Nagaland', pincode: '', category: 'B' },
  { name: 'Mon', state: 'Nagaland', pincode: '', category: 'C' },
  { name: 'Phek', state: 'Nagaland', pincode: '', category: 'C' },
  { name: 'Wokha', state: 'Nagaland', pincode: '', category: 'C' },
  { name: 'Zunheboto', state: 'Nagaland', pincode: '', category: 'C' },
  // Odisha
  { name: 'Balangir', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Baleshwar', state: 'Odisha', pincode: '', category: 'B' },
  { name: 'Baripada', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Bhubaneshwar', state: 'Odisha', pincode: '751001', category: 'A' },
  { name: 'Brahmapur', state: 'Odisha', pincode: '', category: 'B' },
  { name: 'Cuttack', state: 'Odisha', pincode: '753001', category: 'A' },
  { name: 'Dhenkanal', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Kendujhar', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Konark', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Koraput', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Paradip', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Phulabani', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Puri', state: 'Odisha', pincode: '', category: 'C' },
  { name: 'Sambalpur', state: 'Odisha', pincode: '', category: 'B' },
  { name: 'Udayagiri', state: 'Odisha', pincode: '', category: 'C' },
  // Puducherry
  { name: 'Karaikal', state: 'Puducherry', pincode: '', category: 'C' },
  { name: 'Mahe', state: 'Puducherry', pincode: '', category: 'C' },
  { name: 'Puducherry', state: 'Puducherry', pincode: '', category: 'B' },
  { name: 'Yanam', state: 'Puducherry', pincode: '', category: 'C' },
  // Punjab
  { name: 'Amritsar', state: 'Punjab', pincode: '143001', category: 'A' },
  { name: 'Batala', state: 'Punjab', pincode: '', category: 'C' },
  { name: 'Chandigarh', state: 'Punjab', pincode: '160017', category: 'A' },
  { name: 'Faridkot', state: 'Punjab', pincode: '', category: 'C' },
  { name: 'Firozpur', state: 'Punjab', pincode: '', category: 'C' },
  { name: 'Gurdaspur', state: 'Punjab', pincode: '', category: 'C' },
  { name: 'Hoshiarpur', state: 'Punjab', pincode: '', category: 'C' },
  { name: 'Jalandhar', state: 'Punjab', pincode: '144001', category: 'A' },
  { name: 'Kapurthala', state: 'Punjab', pincode: '', category: 'C' },
  { name: 'Ludhiana', state: 'Punjab', pincode: '141001', category: 'A' },
  { name: 'Nabha', state: 'Punjab', pincode: '', category: 'C' },
  { name: 'Patiala', state: 'Punjab', pincode: '147001', category: 'B' },
  { name: 'Rupnagar', state: 'Punjab', pincode: '', category: 'C' },
  { name: 'Sangrur', state: 'Punjab', pincode: '', category: 'C' },
  // Rajasthan
  { name: 'Abu', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Ajmer', state: 'Rajasthan', pincode: '305001', category: 'B' },
  { name: 'Alwar', state: 'Rajasthan', pincode: '301001', category: 'B' },
  { name: 'Amer', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Barmer', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Beawar', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Bharatpur', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Bhilwara', state: 'Rajasthan', pincode: '305001', category: 'B' },
  { name: 'Bikaner', state: 'Rajasthan', pincode: '334001', category: 'B' },
  { name: 'Bundi', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Chittaurgarh', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Churu', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Dhaulpur', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Dungarpur', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Ganganagar', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Hanumangarh', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Jaipur', state: 'Rajasthan', pincode: '302001', category: 'A' },
  { name: 'Jaisalmer', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Jalor', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Jhalawar', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Jhunjhunu', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Jodhpur', state: 'Rajasthan', pincode: '342001', category: 'A' },
  { name: 'Kishangarh', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Kota', state: 'Rajasthan', pincode: '324001', category: 'B' },
  { name: 'Merta', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Nagaur', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Nathdwara', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Pali', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Phalodi', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Pushkar', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Sawai Madhopur', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Shahpura', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Sikar', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Sirohi', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Tonk', state: 'Rajasthan', pincode: '', category: 'C' },
  { name: 'Udaipur', state: 'Rajasthan', pincode: '313001', category: 'B' },
  // Sikkim
  { name: 'Gangtok', state: 'Sikkim', pincode: '', category: 'B' },
  { name: 'Gyalshing', state: 'Sikkim', pincode: '', category: 'C' },
  { name: 'Lachung', state: 'Sikkim', pincode: '', category: 'C' },
  { name: 'Mangan', state: 'Sikkim', pincode: '', category: 'C' },
  // Tamil Nadu
  { name: 'Arcot', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Chengalpattu', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Chennai', state: 'Tamil Nadu', pincode: '600001', category: 'A' },
  { name: 'Chidambaram', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Coimbatore', state: 'Tamil Nadu', pincode: '641001', category: 'A' },
  { name: 'Cuddalore', state: 'Tamil Nadu', pincode: '', category: 'B' },
  { name: 'Dharmapuri', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Dindigul', state: 'Tamil Nadu', pincode: '', category: 'B' },
  { name: 'Erode', state: 'Tamil Nadu', pincode: '638001', category: 'B' },
  { name: 'Kanchipuram', state: 'Tamil Nadu', pincode: '', category: 'B' },
  { name: 'Kanniyakumari', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Kodaikanal', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Kumbakonam', state: 'Tamil Nadu', pincode: '', category: 'B' },
  { name: 'Madurai', state: 'Tamil Nadu', pincode: '625001', category: 'A' },
  { name: 'Mamallapuram', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Nagappattinam', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Nagercoil', state: 'Tamil Nadu', pincode: '', category: 'B' },
  { name: 'Palayamkottai', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Pudukkottai', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Rajapalayam', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Ramanathapuram', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Salem', state: 'Tamil Nadu', pincode: '636001', category: 'A' },
  { name: 'Thanjavur', state: 'Tamil Nadu', pincode: '613001', category: 'B' },
  { name: 'Tiruchchirappalli', state: 'Tamil Nadu', pincode: '620001', category: 'A' },
  { name: 'Tirunelveli', state: 'Tamil Nadu', pincode: '627001', category: 'B' },
  { name: 'Tiruppur', state: 'Tamil Nadu', pincode: '641601', category: 'A' },
  { name: 'Thoothukudi', state: 'Tamil Nadu', pincode: '', category: 'B' },
  { name: 'Udhagamandalam', state: 'Tamil Nadu', pincode: '', category: 'C' },
  { name: 'Vellore', state: 'Tamil Nadu', pincode: '632001', category: 'B' },
  // Telangana
  { name: 'Hyderabad', state: 'Telangana', pincode: '500001', category: 'A' },
  { name: 'Karimnagar', state: 'Telangana', pincode: '', category: 'B' },
  { name: 'Khammam', state: 'Telangana', pincode: '', category: 'B' },
  { name: 'Mahbubnagar', state: 'Telangana', pincode: '', category: 'B' },
  { name: 'Nizamabad', state: 'Telangana', pincode: '', category: 'B' },
  { name: 'Sangareddi', state: 'Telangana', pincode: '', category: 'C' },
  { name: 'Warangal', state: 'Telangana', pincode: '506001', category: 'B' },
  // Tripura
  { name: 'Agartala', state: 'Tripura', pincode: '799001', category: 'B' },
  // Uttar Pradesh
  { name: 'Agra', state: 'Uttar Pradesh', pincode: '282001', category: 'A' },
  { name: 'Aligarh', state: 'Uttar Pradesh', pincode: '202001', category: 'B' },
  { name: 'Amroha', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Ayodhya', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Azamgarh', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Bahraich', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Ballia', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Banda', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Bara Banki', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Bareilly', state: 'Uttar Pradesh', pincode: '243001', category: 'B' },
  { name: 'Basti', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Bijnor', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Bithur', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Budaun', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Bulandshahr', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Deoria', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Etah', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Etawah', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Faizabad', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Farrukhabad-cum-Fatehgarh', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Fatehpur', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Fatehpur Sikri', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Ghaziabad', state: 'Uttar Pradesh', pincode: '201001', category: 'A' },
  { name: 'Ghazipur', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Gonda', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Gorakhpur', state: 'Uttar Pradesh', pincode: '273001', category: 'B' },
  { name: 'Hamirpur', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Hardoi', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Hathras', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Jalaun', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Jaunpur', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Jhansi', state: 'Uttar Pradesh', pincode: '284001', category: 'B' },
  { name: 'Kannauj', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Kanpur', state: 'Uttar Pradesh', pincode: '208001', category: 'A' },
  { name: 'Lakhimpur', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Lalitpur', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Lucknow', state: 'Uttar Pradesh', pincode: '226001', category: 'A' },
  { name: 'Mainpuri', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Mathura', state: 'Uttar Pradesh', pincode: '281001', category: 'B' },
  { name: 'Meerut', state: 'Uttar Pradesh', pincode: '250001', category: 'A' },
  { name: 'Mirzapur-Vindhyachal', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Moradabad', state: 'Uttar Pradesh', pincode: '244001', category: 'B' },
  { name: 'Muzaffarnagar', state: 'Uttar Pradesh', pincode: '251001', category: 'B' },
  { name: 'Partapgarh', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Pilibhit', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Prayagraj', state: 'Uttar Pradesh', pincode: '211001', category: 'A' },
  { name: 'Rae Bareli', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Rampur', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Saharanpur', state: 'Uttar Pradesh', pincode: '247001', category: 'B' },
  { name: 'Sambhal', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Shahjahanpur', state: 'Uttar Pradesh', pincode: '', category: 'B' },
  { name: 'Sitapur', state: 'Uttar Pradesh', pincode: '242001', category: 'B' },
  { name: 'Sultanpur', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Tehri', state: 'Uttar Pradesh', pincode: '', category: 'C' },
  { name: 'Varanasi', state: 'Uttar Pradesh', pincode: '221001', category: 'A' },
  // Uttarakhand
  { name: 'Almora', state: 'Uttarakhand', pincode: '', category: 'C' },
  { name: 'Dehra Dun', state: 'Uttarakhand', pincode: '248001', category: 'B' },
  { name: 'Haridwar', state: 'Uttarakhand', pincode: '249401', category: 'B' },
  { name: 'Mussoorie', state: 'Uttarakhand', pincode: '', category: 'C' },
  { name: 'Nainital', state: 'Uttarakhand', pincode: '', category: 'C' },
  { name: 'Pithoragarh', state: 'Uttarakhand', pincode: '', category: 'C' },
  // West Bengal
  { name: 'Alipore', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Alipur Duar', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Asansol', state: 'West Bengal', pincode: '713301', category: 'B' },
  { name: 'Baharampur', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Bally', state: 'West Bengal', pincode: '', category: 'A' },
  { name: 'Balurghat', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Bankura', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Baranagar', state: 'West Bengal', pincode: '', category: 'A' },
  { name: 'Barasat', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Barrackpore', state: 'West Bengal', pincode: '', category: 'A' },
  { name: 'Basirhat', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Bhatpara', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Bishnupur', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Budge Budge', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Burdwan', state: 'West Bengal', pincode: '713101', category: 'B' },
  { name: 'Chandernagore', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Darjeeling', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Diamond Harbour', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Dum Dum', state: 'West Bengal', pincode: '', category: 'A' },
  { name: 'Durgapur', state: 'West Bengal', pincode: '713201', category: 'B' },
  { name: 'Halisahar', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Haora', state: 'West Bengal', pincode: '711101', category: 'A' },
  { name: 'Hugli', state: 'West Bengal', pincode: '', category: 'A' },
  { name: 'Ingraj Bazar', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Jalpaiguri', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Kalimpong', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Kamarhati', state: 'West Bengal', pincode: '', category: 'A' },
  { name: 'Kanchrapara', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Kharagpur', state: 'West Bengal', pincode: '721301', category: 'B' },
  { name: 'Cooch Behar', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Kolkata', state: 'West Bengal', pincode: '700001', category: 'A' },
  { name: 'Krishnanagar', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Malda', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Midnapore', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Murshidabad', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Nabadwip', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Palashi', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Panihati', state: 'West Bengal', pincode: '743176', category: 'B' },
  { name: 'Purulia', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Raiganj', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Santipur', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Shantiniketan', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Shrirampur', state: 'West Bengal', pincode: '', category: 'B' },
  { name: 'Siliguri', state: 'West Bengal', pincode: '734001', category: 'B' },
  { name: 'Siuri', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Tamluk', state: 'West Bengal', pincode: '', category: 'C' },
  { name: 'Titagarh', state: 'West Bengal', pincode: '', category: 'B' }
];
